### ISSUE TITLE
Some Spanish verbs not conjugating correctly

### ISSUE THREAD

**Issue by conflitz** [SekouDiaoNlp/mlconjug3#66]
**Describe the bug**
So far I've found two Spanish verbs which don't conjugate correctly: parecer (which returns `None` for conjugation except for 3s) and esparcir (which is incorrect in the present subjunctive). 

**To Reproduce**
```
import mlconjug3
es = mlconjug3.Conjugate(language='es')
conj_parecer = es.conjugate("parecer")
for conj in conj_parecer.iterate():
    print(conj)
conj_esparcir = es.conjugate("esparcir")
print(conj_esparcir.conjug_info['Subjuntivo']['Subjuntivo presente'])
```

**Expected behavior**
Parecer should outputs conjugations for conjugations besides the singular third person; esparcir conjugations in the subjunctive present should have the letter z instead of a c (e.g. esparca should be esparza).

**Comment by SekouDiaoNlp** [comment]
Hi @conflitz  , thanks for submitting this bug report.

I will investigate the issue over the weekend and l will let you know when I release the new version with the fix.

Thanks for using mlconjug3.

SekouDiaoNlp.

**Comment by SekouDiaoNlp** [comment]
Hi @conflitz   I just pushed the fix for this issue and issue on the master branch here on GitHub.

I am very sorry for the delay but with the coronavirus pandemic I didn't have much time to work on my open source projects.

I also published a fix for this issue today and released a new version of mlconjug3 on PyPi.

You can install the new version by typing the following command in your terminal:
`pip install mlconjug3`

Thanks again for using mlconjug3 and for submitting bug reports.

Cheers,

SekouDiaoNlp.
